### ISSUE TITLE
Bug #1

### ISSUE THREAD

**Issue by Erwann9875** [Flowx3/nos4delauncher#2]
Impossible to find the column 2

**Comment by Erwann9875** [comment]
Found ! 

           cmd = New MySqlCommand("SELECT * FROM `launcher`", c)
            da = New MySqlDataAdapter(cmd)
            da.Fill(ds, "launcher")
            IP = ds.Tables(0).Rows(0).Item(1)
            Port = ds.Tables(0).Rows(0).Item(2)

    replace for

            cmd = New MySqlCommand("SELECT * FROM `launcher`", c)
            da = New MySqlDataAdapter(cmd)
            da.Fill(ds, "launcher")
            IP = ds.Tables(0).Rows(0).Item(0)
            Port = ds.Tables(0).Rows(0).Item(1)

**Comment by Flowx3** [comment]
Fixed!
